version: '2'
services:
  app:
    container_name: invest_notification_service
    image: invest_notification_service
    build: .
    networks:
      - main_network
    ports:
      - "8084:8084"
    volumes:
      # - ${PWD}/app/node_modules
      - /app/node_modules
      - .:/app
    stdin_open: true

  redis:
    container_name: invest_notification_redis
    image: redis
    logging:
      driver: none
    ports:
      - "6379"
    networks:
      - main_network

  mongo:
    container_name: invest_notification_mongo
    image: mongo
    volumes:
      - /data/db/mongo
    ports:
      - "27018:27017"
    networks:
      - main_network

volumes:
  node_modules:


networks:
  main_network:
    driver: bridge
